doc/nginx-local-auth2-example.conf
src/plugin/modules/account/tokenManager.js
src/plugin/modules/linkContinue.js
src/plugin/modules/loginContinue.js

- added current token to token manager
- minor code cleanup
- added local auth2 nginx config example

improvements

---

src/plugin/modules/account/agreementsManager.js
src/plugin/modules/loginContinue.js
src/plugin/modules/userAgreements.js

- titles for linkall and agreements
- exclude current auth id in linkall list

improve login-continue

---

src/plugin/modules/account/signinManager.js
src/plugin/modules/linkContinue.js
src/plugin/modules/login.js
src/plugin/modules/loginWidget.js

Linking was plain broken.
Also needed ci config changes to fix google linking. The settings should always route back to the link-choice page.
Fixed the service token lifetime. 99,999,999,999 days was too many for javascript -- 100 years or 36,500 is plenty.
Also improved the sign-in management page to show the browser and os for the user agent used to create the token - thanks Gavin :)

Fix linking, improve sign-in management

---

src/plugin/config.yml
src/plugin/modules/account/components/profileEditor.js
src/plugin/modules/account/components/userInfoEditor.js
src/plugin/modules/account/panel.js
src/plugin/modules/account/personalInfoEditorKO.js
src/plugin/modules/account/profileManager.js
src/plugin/modules/account/signinManager.js
src/plugin/modules/linkContinue.js
src/plugin/modules/signinWidget.js
src/plugin/resources/css/main.css
src/plugin/resources/data/institutions.csv

- editor updates
- added jobTitle, researchInterests, and big csv of institutions
- note: need to fix the typeahead control
implements TASK-472

many changes to support the new user profile

---

src/plugin/modules/account/components/profileEditor.js
src/plugin/modules/components/loginView.js
src/plugin/modules/components/typeaheadInput.js
src/plugin/modules/lib/fieldBuilders.js

- still consider this experimental, but it does appear to work well with 4K+ items

Update orgnaization selection to typeahead (search) control

---

src/plugin/modules/account/signinManager.js

Make table header consistent for IP address in sign-ins tab

---

src/plugin/modules/components/loginView.js
src/plugin/modules/components/signinForm.js
src/plugin/modules/components/signinView.js
src/plugin/modules/components/signupView.js
src/plugin/modules/signedout.js

- sign-in widget
- sign-up page, first step (select provider)
implements TASK-752

Re-order google above globus when a choice is provided

---

src/plugin/modules/components/signinForm.js
src/plugin/modules/components/signinView.js
src/plugin/modules/components/signupView.js
src/plugin/modules/loginContinueKO.js
src/plugin/resources/css/main.css

- will need another pass at messaging I'm sure.
implements TASK-751

Refactor warning messages on signin, signup regarding inadvertent usage of a Globus or Google account.

---

src/plugin/modules/components/loginView.js
src/plugin/modules/components/policyComponent.js
src/plugin/modules/components/signinView.js
src/plugin/modules/components/signupComponent.js
src/plugin/modules/components/signupView.js
src/plugin/modules/loginContinueKO.js
src/plugin/resources/css/main.css

Ui fixes and improvements

---

src/plugin/modules/login.css

in support of TASK-472, I suppose.

Limit login window to 1024 pixels

---

src/plugin/config.yml
src/plugin/modules/account/components/profileEditor.js
src/plugin/modules/account/panel.js
src/plugin/modules/components/loginView.js
src/plugin/modules/login.js

save button at top (just a start, more changes coming)
new "authorization required" tab if signin is forced by accessing a protected path
implements TASK-472, TASK-736

account manager, profile editor tab first

---

src/plugin/modules/components/loginView.js
src/plugin/modules/login.js

- it is now the default path in the ui
- if no authorization, it handles signin
- if authorization, routes to dashboard
- previously relied on the ui routing to the dashboard by default
continuing support for TASK-472

Improve path handling in login view

---

src/plugin/config.yml
src/plugin/modules/account/components/profileEditor.js
src/plugin/modules/account/personalInfoEditorKO.js
src/plugin/modules/account/profileManager.js
src/plugin/modules/components/policyComponent.js
src/plugin/modules/components/signinView.js
src/plugin/modules/components/signupComponent.js
src/plugin/modules/components/signupView.js
src/plugin/modules/lib/fieldBuilders.js
src/plugin/modules/login.js
src/plugin/modules/loginContinueKO.js
src/plugin/modules/signup.js

- they are now loaded globally through the plugin config

Remove KO component amd dependencies

---

src/plugin/modules/components/loginView.js

Fix initial login page load error

---

src/plugin/modules/account/components/profileEditor.js
src/plugin/modules/account/panel.js
src/plugin/modules/components/loginView.js
src/plugin/modules/components/profileView.js
src/plugin/modules/loginContinueKO.js
src/plugin/modules/signinWidget.js
src/plugin/resources/dataSources/avatarOptions.json

subdue colors in header for profile editor
rename "mysteryman" to "silhouette" for anonymous non-gravatar avatar
minor code cleanup
in suport ot TASK-758

minor ui improvements

---

src/plugin/modules/account/linksManager.js
src/plugin/modules/components/loginView.js
src/plugin/modules/components/signinView.js
src/plugin/modules/components/signupView.js
src/plugin/modules/config.yml
src/plugin/modules/lib/utils.js
src/plugin/resources/data/config.yml

- also minor code cleanup, remove comments

Update launch date to 6/7 -- use config only not hard coded

---

src/plugin/modules/account/components/profileEditor.js
src/plugin/modules/components/profileView.js
src/plugin/modules/signinWidget.js
src/plugin/modules/signup.js
src/plugin/plugin

fix next request in signin via signup
code cleanup

Improve gravatar behavior in editor

---

src/plugin/modules/components/loginView.js

- simplify text
- replace link to legacy page with link to announcement blog post

Simplify login view content

---

src/plugin/modules/account/linksManager.js
src/plugin/modules/linkContinue.js

- adapt to new link choice api changes
- improve logic of the countdown clock
- improved clock timeout behavior
- adapt to new notification api (to handle timeout)

linking update

---

src/plugin/modules/components/signupForm.js
src/plugin/modules/components/signupView.js
src/plugin/modules/linkContinue.js
src/plugin/modules/loginContinue.js
src/plugin/modules/signup.js

- launch date was missing on the Globus signup help text
- signup form's signup button changed to 'button' from 'submit' to prevent form from trying to submit with the Enter key
- changed warning notification type label from 'warn' to 'warning' since that was the original label (and now matches the notification widget)

Minor fixes

---

src/plugin/modules/components/loginView.js
src/plugin/modules/components/signupView.js
src/plugin/resources/css/main.css

- video embed is the Narrative Interface video as a stand-in. The sign-in video will be ready tomorrow.

text changes and video embed on sign-in page

---

src/plugin/modules/loginContinue.js

- the dom's URL api is not as widespread or as uniform as it might appear to be.

Replace usage of URL dom api with own URL function

---

src/plugin/modules/components/loginView.js
src/plugin/modules/linkContinue.js

- updated sign-in intro video
- improved text on linking

UI updates

---

src/plugin/modules/linkContinue.js

- fixes a bug where the expiration notification pops up if you logout when in the middle of linking

linking - stop countdown clock upon widget top

---

src/plugin/modules/account/components/profileEditor.js
src/plugin/modules/lib/fieldBuilders.js
src/plugin/modules/linkContinue.js

Show message next to save button if can't save; fix error message display

---

src/plugin/modules/components/signupForm.js

- I suspect this is due to the new way that components are loaded through the plugin -- it changes the component loading from just-in-time to ahead-of-time, so a closed-over variable which would otherwise have a value now did not.
- solved by placing the variable definition above the function definition which closes over it.

Fix signup form

---

src/plugin/modules/components/signupView.js

about signing up, to address https://kbase-jira.atlassian.net/browse/PTV-373
NOTE: I'm not sure of the syntax for including html in the text messages -- there may be some special way to do it (I couldn't find any relevant examples), so someone (e.g., @eapearson ) may have to fix my addition to line 47.

Improved wording

---

src/plugin/modules/widgets/signinWidget.js

add missing method [SCT-518]

---

src/plugin/config.yml

- now required in order to be included in the sidebar nav
- other minor changes to simplify the config

updated plugin config, adds account menu [SCT-554]

---

src/plugin/modules/components/loginView.js

- otherwise it displays poorly when the authorization required tab shows

login view set to fixed with [SCT-630]

---

src/plugin/modules/components/loginView.js
src/plugin/modules/components/signinButton.js
src/plugin/modules/components/signupView.js
src/plugin/modules/login.js
src/plugin/modules/signup.js

- define dom node attributes which allow deterministic paths to testable elements

changes to support ui integration testing

---

src/plugin/test/main.json

- doesn't do much, but partially confirms basic sigin and signup buttons work
- more a test of the new integration test machinery in kbase-ui

add basic integration test

---

src/plugin/modules/account/linksManager.js
src/plugin/modules/components/loginView.js
src/plugin/modules/components/signinForm.js
src/plugin/modules/components/signinView.js
src/plugin/modules/components/signupView.js
src/plugin/modules/lib/provider.js
src/plugin/modules/loginContinue.js
src/plugin/modules/signedout.js
src/plugin/resources/data/providers.json

- uses the "allow" tag mechanism, filtering on "alpha" which is essentially synonymous with CI.

disable orcid signup/signup outside of CI [SCT-1075]

---

src/plugin/config.yml
src/plugin/modules/account/panel.js
src/plugin/modules/account/profileManager.js
src/plugin/modules/widgets/tabsWidget.js

- exposed by the ui's main nav now reloading panels
- spamming the menu causes overlapping render requests

fix race in unmounting accounts panel

---

src/plugin/config.yml

- not sure why it has worked until now!

make signup url "step" param optional

---

src/plugin/iframe_root/modules/components/errorView.js
src/plugin/iframe_root/modules/components/signinForm.js
src/plugin/iframe_root/modules/components/signinView.js
src/plugin/iframe_root/modules/loginContinue.js
src/plugin/iframe_root/modules/vendor/kbase-common-es6/reactiveDb.js

- now catches more errors and displays an error message
- helpful when debugging malformed login requests, which is not an issue in the plugin, but may be for outside login start requests.

improve login handling of malformed login start requests.

---

src/plugin/iframe_root/modules/reactComponents/TypeaheadInput.css
src/plugin/iframe_root/modules/reactComponents/TypeaheadInput.js

still seeking the bad behavior

a bit more refinement [UFI-60]
